spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081/
          predicates:
            - Path=/users/login,/users/signup
        - id: write
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**,/feeds/**
            - Method=POST,PATCH,PUT,DELETE
          filters:
            - AuthenticationFilter
        - id: read
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**,/feeds/**
            - Method=GET
          filters:
            - AuthenticationFilter



jwt:
  secret: ${JWT_SECRET}
  prefix: ${JWT_PREFIX:Bearer }